[alias]
xtask = "run --quiet --package xtask --"

# compiling from OS X: https://github.com/FiloSottile/homebrew-musl-cross
[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"